package com.sketcher.sketchercompanionv1.tools

import android.graphics.Canvas
import android.graphics.Paint
import com.sketcher.sketchercompanionv1.VectorStroke

/**
 * Interface for polymorphically rendering a stroke on a Canvas.
 */
interface BrushRenderer {
    fun draw(
        canvas: Canvas,
        stroke: VectorStroke,
        paint: Paint,
        alphaMultiplier: Float,
        zoom: Float = 1.0f,
        applyFillStyleFunc: (Paint, Float) -> Unit
    )
}

/**
 * Renders meshes generated by Perfect Freehand (Pencil, Pen, Pluma, etc.).
 * Draws using Paint.Style.FILL on the generated outline polygon.
 */
class MeshBrushRenderer : BrushRenderer {
    override fun draw(
        canvas: Canvas,
        stroke: VectorStroke,
        paint: Paint,
        alphaMultiplier: Float,
        zoom: Float,
        applyFillStyleFunc: (Paint, Float) -> Unit
    ) {
        paint.style = Paint.Style.FILL
        applyFillStyleFunc(paint, alphaMultiplier)
        canvas.drawPath(stroke.path, paint)
        if (stroke.paths.isNotEmpty()) {
            for (p in stroke.paths) {
                canvas.drawPath(p, paint)
            }
        }
    }
}

/**
 * Renders standard line outlines (Paint tool).
 * Draws using Paint.Style.STROKE on the stroke centerline.
 */
class OutlineBrushRenderer : BrushRenderer {
    override fun draw(
        canvas: Canvas,
        stroke: VectorStroke,
        paint: Paint,
        alphaMultiplier: Float,
        zoom: Float,
        applyFillStyleFunc: (Paint, Float) -> Unit
    ) {
        val settings = stroke.settings
        val outlineWidth = when (settings) {
            is PaintSettings -> settings.size * settings.paintOutlineWidthRatio
            is WatercolorSettings -> settings.size * settings.paintOutlineWidthRatio
            else -> 2f
        }
        paint.style = Paint.Style.STROKE
        applyFillStyleFunc(paint, alphaMultiplier)
        paint.strokeWidth = outlineWidth
        paint.pathEffect = null
        canvas.drawPath(stroke.path, paint)
    }
}

/**
 * Renders watercolor bleed and blur effects with optional edge clipping.
 */
class WatercolorBrushRenderer : BrushRenderer {
    companion object {
        private val blurFilterCache = java.util.concurrent.ConcurrentHashMap<Int, android.graphics.BlurMaskFilter>()

        private fun getBlurMaskFilter(radius: Float): android.graphics.BlurMaskFilter {
            val clampedRadius = radius.coerceAtLeast(0.01f)
            val key = (clampedRadius * 10f).toInt() // Quantize to 0.1 increments for maximum reuse
            return blurFilterCache.getOrPut(key) {
                android.graphics.BlurMaskFilter(
                    clampedRadius,
                    android.graphics.BlurMaskFilter.Blur.NORMAL
                )
            }
        }
    }

    override fun draw(
        canvas: Canvas,
        stroke: VectorStroke,
        paint: Paint,
        alphaMultiplier: Float,
        zoom: Float,
        applyFillStyleFunc: (Paint, Float) -> Unit
    ) {
        val settings = stroke.settings as? WatercolorSettings ?: return
        val strokeSeed = stroke.seed
        val jitteredPath = stroke.getJitteredPath(strokeSeed)

        paint.style = Paint.Style.STROKE
        applyFillStyleFunc(paint, alphaMultiplier * settings.watercolorCenterOpacity)
        paint.strokeWidth = settings.size * settings.paintOutlineWidthRatio
        paint.pathEffect = null
        
        val blurRadius = (settings.size * settings.watercolorBlurRadiusRatio).coerceAtLeast(0.01f)
        paint.maskFilter = getBlurMaskFilter(blurRadius)

        if (settings.watercolorEdgeMode == com.sketcher.sketchercompanionv1.dto.WatercolorEdgeMode.INSIDE) {
            canvas.save()
            canvas.clipPath(stroke.path)
            canvas.drawPath(jitteredPath, paint)
            canvas.restore()
        } else if (settings.watercolorEdgeMode == com.sketcher.sketchercompanionv1.dto.WatercolorEdgeMode.OUTSIDE) {
            canvas.save()
            canvas.clipOutPath(stroke.path)
            canvas.drawPath(jitteredPath, paint)
            canvas.restore()
        } else {
            canvas.drawPath(jitteredPath, paint)
        }

        paint.pathEffect = null
        paint.maskFilter = null
    }
}


