package com.sketcher.sketchercompanionv1.tools

import android.graphics.Canvas
import android.graphics.Paint
import com.sketcher.sketchercompanionv1.VectorStroke

/**
 * Interface for polymorphically rendering a stroke on a Canvas.
 */
interface BrushRenderer {
    fun draw(
        canvas: Canvas,
        stroke: VectorStroke,
        paint: Paint,
        alphaMultiplier: Float,
        applyFillStyleFunc: (Paint, Float) -> Unit
    )
}

/**
 * Renders meshes generated by Perfect Freehand (Pencil, Pen, Pluma, etc.).
 * Draws using Paint.Style.FILL on the generated outline polygon.
 */
class MeshBrushRenderer : BrushRenderer {
    override fun draw(
        canvas: Canvas,
        stroke: VectorStroke,
        paint: Paint,
        alphaMultiplier: Float,
        applyFillStyleFunc: (Paint, Float) -> Unit
    ) {
        paint.style = Paint.Style.FILL
        applyFillStyleFunc(paint, alphaMultiplier)
        canvas.drawPath(stroke.path, paint)
        if (stroke.paths.isNotEmpty()) {
            for (p in stroke.paths) {
                canvas.drawPath(p, paint)
            }
        }
    }
}

/**
 * Renders standard line outlines (Paint tool).
 * Draws using Paint.Style.STROKE on the stroke centerline.
 */
class OutlineBrushRenderer : BrushRenderer {
    override fun draw(
        canvas: Canvas,
        stroke: VectorStroke,
        paint: Paint,
        alphaMultiplier: Float,
        applyFillStyleFunc: (Paint, Float) -> Unit
    ) {
        val settings = stroke.settings
        val outlineWidth = when (settings) {
            is PaintSettings -> settings.paintOutlineWidth
            is WatercolorSettings -> settings.paintOutlineWidth
            else -> 2f
        }
        paint.style = Paint.Style.STROKE
        applyFillStyleFunc(paint, alphaMultiplier)
        paint.strokeWidth = outlineWidth
        paint.pathEffect = null
        canvas.drawPath(stroke.path, paint)
    }
}

/**
 * Renders watercolor bleed and blur effects with optional edge clipping.
 */
class WatercolorBrushRenderer : BrushRenderer {
    override fun draw(
        canvas: Canvas,
        stroke: VectorStroke,
        paint: Paint,
        alphaMultiplier: Float,
        applyFillStyleFunc: (Paint, Float) -> Unit
    ) {
        val settings = stroke.settings as? WatercolorSettings ?: return
        val strokeSeed = stroke.hashCode().toLong()
        val jitteredPath = stroke.getJitteredPath(strokeSeed)

        paint.style = Paint.Style.STROKE
        applyFillStyleFunc(paint, alphaMultiplier * settings.watercolorCenterOpacity)
        paint.strokeWidth = settings.paintOutlineWidth
        paint.pathEffect = null
        paint.maskFilter = android.graphics.BlurMaskFilter(
            settings.watercolorBlurRadius.coerceAtLeast(0.01f),
            android.graphics.BlurMaskFilter.Blur.NORMAL
        )

        if (settings.watercolorEdgeMode == com.sketcher.sketchercompanionv1.dto.WatercolorEdgeMode.INSIDE) {
            canvas.save()
            canvas.clipPath(stroke.path)
            canvas.drawPath(jitteredPath, paint)
            canvas.restore()
        } else if (settings.watercolorEdgeMode == com.sketcher.sketchercompanionv1.dto.WatercolorEdgeMode.OUTSIDE) {
            canvas.save()
            canvas.clipOutPath(stroke.path)
            canvas.drawPath(jitteredPath, paint)
            canvas.restore()
        } else {
            canvas.drawPath(jitteredPath, paint)
        }

        paint.pathEffect = null
        paint.maskFilter = null
    }
}
